const SUBJECT_PHRASES = new Map([
  [
    "English",
    [
      "figure of speech",
      "parts of speech",
      "subject verb agreement",
      "direct speech",
      "indirect speech",
      "passive voice",
      "active voice",
      "literary device",
      "main character",
      "theme of the story",
      "summary of the poem",
      "rhyming words",
      "opposite words",
      "synonyms and antonyms",
      "reading comprehension",
      "story writing",
      "letter writing",
    ],
  ],
  [
    "Hindi",
    [
      "vilom shabd",
      "paryayvachi shabd",
      "samas",
      "sandhi",
      "mohavare",
      "kahani lekhan",
      "patra lekhan",
      "anuchhed lekhan",
      "dohe",
      "kavita",
      "vyakaran",
      "sangya",
      "sarvanam",
      "visheshan",
      "kriya",
    ],
  ],
  [
    "Mathematics",
    [
      "pythagorean theorem",
      "quadratic equation",
      "area of circle",
      "volume of sphere",
      "mean median mode",
      "probability distribution",
      "differential equation",
      "integration by parts",
      "matrix multiplication",
      "law of sines",
      "law of cosines",
      "addition and subtraction",
      "multiplication table",
      "division of numbers",
      "word problems",
      "geometry shapes",
      "number line",
      "place value",
      "fractions and decimals",
    ],
  ],
  [
    "Physics",
    [
      "law of motion",
      "newton's first law",
      "newton's second law",
      "newton's third law",
      "law of inertia",
      "law of gravitation",
      "speed of light",
      "ohm's law",
      "bernoulli's principle",
      "law of conservation of energy",
      "law of conservation of momentum",
      "snell's law",
      "hooke's law",
      "magnetic field",
      "electric circuit",
      "simple machines",
      "types of forces",
    ],
  ],
  [
    "Chemistry",
    [
      "periodic table",
      "chemical reaction",
      "acid base reaction",
      "atomic number",
      "molecular formula",
      "chemical bonding",
      "redox reaction",
      "organic compound",
      "inorganic compound",
      "law of definite proportions",
      "law of multiple proportions",
      "states of matter",
      "separation of mixtures",
      "physical and chemical change",
    ],
  ],
  [
    "Biology",
    [
      "cell division",
      "cell membrane",
      "photosynthesis",
      "genetic code",
      "dna replication",
      "protein synthesis",
      "food chain",
      "food web",
      "natural selection",
      "human genome",
      "blood circulation",
      "respiratory system",
      "nervous system",
      "immune system",
      "parts of a plant",
      "parts of a flower",
      "life cycle of butterfly",
      "digestive system",
    ],
  ],
  [
    "History",
    [
      "world war i",
      "world war ii",
      "french revolution",
      "industrial revolution",
      "american civil war",
      "ancient egypt",
      "roman empire",
      "indian independence",
      "cold war",
      "treaty of versailles",
      "fall of berlin wall",
      "mughal empire",
      "mauryan empire",
      "ashoka the great",
      "freedom fighters of india",
      "harappan civilization",
    ],
  ],
  [
    "Geography",
    [
      "mount everest",
      "sahara desert",
      "amazon river",
      "ganges river",
      "great barrier reef",
      "latitude and longitude",
      "prime meridian",
      "tropic of cancer",
      "tropic of capricorn",
      "international date line",
      "continents and oceans",
      "climate zones",
      "natural resources",
      "types of soil",
      "water cycle",
    ],
  ],
  [
    "Civics",
    [
      "fundamental rights",
      "directive principles",
      "constitution of india",
      "election commission",
      "parliament of india",
      "supreme court of india",
      "roles of citizens",
      "government structure",
      "local self government",
      "panchayati raj",
      "democracy in india",
    ],
  ],
  [
    "Economics",
    [
      "law of demand",
      "law of supply",
      "gross domestic product",
      "inflation rate",
      "market equilibrium",
      "opportunity cost",
      "fiscal policy",
      "monetary policy",
      "balance of payments",
      "foreign exchange rate",
      "types of resources",
      "barter system",
      "money and banking",
      "needs and wants",
    ],
  ],
  [
    "Political Science",
    [
      "current president",
      "current prime minister",
      "president of india",
      "prime minister of india",
      "head of state",
      "separation of powers",
      "united nations",
      "security council",
      "general assembly",
      "political party",
      "universal adult franchise",
      "voting rights",
      "role of government",
    ],
  ],
  [
    "Computer Science",
    [
      "binary search",
      "bubble sort",
      "linked list",
      "object oriented programming",
      "relational database",
      "operating system",
      "machine learning",
      "artificial intelligence",
      "network protocol",
      "encryption algorithm",
      "data structure",
      "parts of computer",
      "input and output devices",
      "uses of computer",
      "internet safety",
    ],
  ],
  [
    "General Knowledge",
    [
      "nobel prize winner",
      "largest country",
      "smallest country",
      "longest river",
      "highest mountain",
      "current affairs",
      "world record",
      "guinness book",
      "olympic games",
      "world cup winner",
      "currency of",
      "national symbols of india",
      "famous personalities",
      "important days",
      "inventions and discoveries",
    ],
  ],
  [
    "Environmental Science",
    [
      "save water",
      "save trees",
      "reduce reuse recycle",
      "pollution control",
      "types of pollution",
      "parts of a plant",
      "living and nonliving things",
      "our environment",
      "natural resources",
      "seasons of the year",
      "food chain",
      "importance of cleanliness",
    ],
  ],
  [
    "Sanskrit",
    [
      "shabd roop",
      "dhatu roop",
      "sandhi viched",
      "samas",
      "subhashitani",
      "kavita",
      "patra lekhan",
      "anuchhed lekhan",
      "vyakaran",
    ],
  ],
  [
    "Moral Science",
    [
      "good manners",
      "moral values",
      "honesty is the best policy",
      "helping others",
      "respect elders",
      "importance of discipline",
      "truthfulness",
      "teamwork",
      "kindness",
    ],
  ],
  [
    "Art",
    [
      "primary colors",
      "color wheel",
      "types of painting",
      "famous artists",
      "drawing techniques",
      "origami",
      "craft work",
      "art competition",
    ],
  ],
  [
    "Music",
    [
      "musical notes",
      "types of instruments",
      "famous musicians",
      "national anthem",
      "folk songs",
      "classical music",
      "singing competition",
    ],
  ],
  [
    "Physical Education",
    [
      "types of sports",
      "olympic games",
      "physical exercise",
      "importance of sports",
      "famous athletes",
      "yoga asanas",
      "team games",
      "sportsmanship",
    ],
  ],
]);

const SUBJECT_KEYWORDS = new Map([
  [
    "English",
    [
      "grammar",
      "literature",
      "poem",
      "prose",
      "verb",
      "noun",
      "adjective",
      "adverb",
      "sentence",
      "paragraph",
      "essay",
      "novel",
      "play",
      "drama",
      "author",
      "theme",
      "character",
      "english",
      "summary",
      "synonym",
      "antonym",
      "story",
      "letter",
      "comprehension",
      "rhyme",
      "opposite",
    ],
  ],
  [
    "Hindi",
    [
      "vilom",
      "paryayvachi",
      "samas",
      "sandhi",
      "mohavare",
      "kahani",
      "patra",
      "anuchhed",
      "dohe",
      "kavita",
      "vyakaran",
      "sangya",
      "sarvanam",
      "visheshan",
      "kriya",
      "hindi",
      "shabd",
    ],
  ],
  [
    "Mathematics",
    [
      "algebra",
      "calculus",
      "geometry",
      "equation",
      "integral",
      "derivative",
      "matrix",
      "probability",
      "statistics",
      "theorem",
      "function",
      "trigonometry",
      "arithmetic",
      "vector",
      "limit",
      "logarithm",
      "math",
      "number",
      "fraction",
      "addition",
      "subtraction",
      "multiplication",
      "division",
      "table",
      "shape",
      "angle",
      "triangle",
      "circle",
      "square",
      "rectangle",
      "polygon",
      "ratio",
      "proportion",
      "decimal",
      "percent",
      "average",
    ],
  ],
  [
    "Physics",
    [
      "newton",
      "force",
      "acceleration",
      "velocity",
      "energy",
      "motion",
      "gravity",
      "friction",
      "mass",
      "inertia",
      "work",
      "power",
      "momentum",
      "thermodynamics",
      "optics",
      "magnetism",
      "electricity",
      "wave",
      "quantum",
      "relativity",
      "joule",
      "watt",
      "pascal",
      "ampere",
      "coulomb",
      "tesla",
      "faraday",
      "galileo",
      "kepler",
      "planck",
      "bohr",
      "machine",
      "magnet",
      "circuit",
      "light",
      "sound",
      "pressure",
    ],
  ],
  [
    "Chemistry",
    [
      "atom",
      "molecule",
      "reaction",
      "acid",
      "base",
      "periodic",
      "element",
      "compound",
      "bond",
      "chemical",
      "catalyst",
      "salt",
      "organic",
      "inorganic",
      "solution",
      "solvent",
      "solute",
      "oxidation",
      "reduction",
      "chemistry",
      "isotope",
      "alkali",
      "alkaline",
      "halogen",
      "noble gas",
      "anion",
      "cation",
      "ester",
      "polymer",
      "mixture",
      "change",
      "matter",
      "gas",
      "liquid",
      "solid",
    ],
  ],
  [
    "Biology",
    [
      "cell",
      "dna",
      "gene",
      "evolution",
      "plant",
      "animal",
      "respiration",
      "enzyme",
      "protein",
      "chromosome",
      "mitosis",
      "meiosis",
      "ecosystem",
      "organism",
      "bacteria",
      "virus",
      "genetics",
      "biology",
      "reproduction",
      "photosynthesis",
      "chlorophyll",
      "mitochondria",
      "ribosome",
      "nucleus",
      "heredity",
      "mutation",
      "species",
      "taxonomy",
      "flower",
      "root",
      "leaf",
      "stem",
      "organ",
      "system",
    ],
  ],
  [
    "History",
    [
      "revolution",
      "war",
      "empire",
      "dynasty",
      "treaty",
      "independence",
      "ancient",
      "medieval",
      "modern",
      "colony",
      "civilization",
      "historical",
      "king",
      "queen",
      "battle",
      "constitution",
      "monarchy",
      "democracy",
      "history",
      "era",
      "pharaoh",
      "sultan",
      "czar",
      "president",
      "prime minister",
      "governor",
      "treaty",
      "alliance",
      "confederation",
      "freedom",
      "civilization",
      "ashoka",
      "mughal",
      "harappa",
    ],
  ],
  [
    "Geography",
    [
      "continent",
      "river",
      "mountain",
      "climate",
      "map",
      "latitude",
      "longitude",
      "ocean",
      "desert",
      "island",
      "country",
      "state",
      "city",
      "capital",
      "geography",
      "region",
      "valley",
      "plateau",
      "glacier",
      "volcano",
      "delta",
      "peninsula",
      "archipelago",
      "basin",
      "plain",
      "hill",
      "fjord",
      "reef",
      "soil",
      "resource",
      "weather",
      "rainfall",
    ],
  ],
  [
    "Civics",
    [
      "democracy",
      "constitution",
      "election",
      "parliament",
      "law",
      "rights",
      "government",
      "policy",
      "politics",
      "state",
      "citizen",
      "vote",
      "minister",
      "president",
      "political",
      "legislation",
      "judiciary",
      "executive",
      "cabinet",
      "assembly",
      "senate",
      "congress",
      "diplomacy",
      "treaty",
      "ambassador",
      "federal",
      "republic",
      "civic",
      "panchayat",
      "municipal",
      "governance",
    ],
  ],
  [
    "Economics",
    [
      "supply",
      "demand",
      "inflation",
      "gdp",
      "market",
      "trade",
      "currency",
      "economy",
      "microeconomics",
      "macroeconomics",
      "recession",
      "stock",
      "bond",
      "interest",
      "tax",
      "budget",
      "cost",
      "profit",
      "loss",
      "economics",
      "tariff",
      "quota",
      "export",
      "import",
      "monopoly",
      "oligopoly",
      "competition",
      "dividend",
      "resource",
      "bank",
      "money",
      "barter",
    ],
  ],
  [
    "Political Science",
    [
      "democracy",
      "constitution",
      "election",
      "parliament",
      "law",
      "rights",
      "government",
      "policy",
      "politics",
      "state",
      "citizen",
      "vote",
      "minister",
      "president",
      "political",
      "legislation",
      "judiciary",
      "executive",
      "cabinet",
      "assembly",
      "senate",
      "congress",
      "diplomacy",
      "treaty",
      "ambassador",
      "federal",
      "republic",
      "franchise",
      "party",
      "commission",
      "governance",
    ],
  ],
  [
    "Computer Science",
    [
      "algorithm",
      "binary",
      "programming",
      "database",
      "network",
      "software",
      "hardware",
      "computer",
      "encryption",
      "compiler",
      "variable",
      "loop",
      "function",
      "array",
      "object",
      "class",
      "python",
      "java",
      "c++",
      "javascript",
      "html",
      "css",
      "sql",
      "json",
      "api",
      "recursion",
      "stack",
      "queue",
      "tree",
      "graph",
      "input",
      "output",
      "device",
      "internet",
      "safety",
    ],
  ],
  [
    "General Knowledge",
    [
      "quiz",
      "gk",
      "general knowledge",
      "current affairs",
      "fact",
      "trivia",
      "world",
      "knowledge",
      "award",
      "record",
      "festival",
      "event",
      "celebrity",
      "sports",
      "olympics",
      "currency",
      "capital",
      "anthem",
      "flag",
      "emblem",
      "logo",
      "mascot",
      "invention",
      "discovery",
      "personality",
      "day",
      "symbol",
      "famous",
      "important",
    ],
  ],
  [
    "Environmental Science",
    [
      "environment",
      "pollution",
      "resource",
      "plant",
      "animal",
      "water",
      "air",
      "soil",
      "cleanliness",
      "recycle",
      "reduce",
      "reuse",
      "season",
      "living",
      "nonliving",
      "cycle",
      "nature",
      "tree",
      "forest",
      "rain",
      "weather",
      "climate",
      "waste",
      "energy",
    ],
  ],
  [
    "Sanskrit",
    [
      "shabd",
      "dhatu",
      "sandhi",
      "samas",
      "subhashit",
      "kavita",
      "patra",
      "anuchhed",
      "vyakaran",
      "sanskrit",
    ],
  ],
  [
    "Moral Science",
    [
      "moral",
      "value",
      "manners",
      "honesty",
      "help",
      "respect",
      "discipline",
      "truth",
      "teamwork",
      "kindness",
      "good",
      "bad",
      "behavior",
      "ethics",
    ],
  ],
  [
    "Art",
    [
      "color",
      "painting",
      "artist",
      "drawing",
      "origami",
      "craft",
      "art",
      "competition",
      "sketch",
      "design",
      "pattern",
      "brush",
      "canvas",
    ],
  ],
  [
    "Music",
    [
      "music",
      "note",
      "instrument",
      "musician",
      "anthem",
      "song",
      "folk",
      "classical",
      "singing",
      "competition",
      "melody",
      "rhythm",
      "tune",
    ],
  ],
  [
    "Physical Education",
    [
      "sport",
      "game",
      "exercise",
      "athlete",
      "yoga",
      "team",
      "sportsmanship",
      "olympic",
      "run",
      "jump",
      "throw",
      "fitness",
      "training",
      "competition",
    ],
  ],
]);

// Phrase-first, then keyword matching. If no match, default to General Knowledge.
export function detectSubject(question) {
  if (!question || typeof question !== "string") return "General";
  const text = question.toLowerCase();
  // Phrase matching (context-aware)
  for (const [subject, phrases] of SUBJECT_PHRASES.entries()) {
    for (const phrase of phrases) {
      if (text.includes(phrase)) {
        return subject;
      }
    }
  }
  // Keyword matching
  for (const [subject, keywords] of SUBJECT_KEYWORDS.entries()) {
    for (const keyword of keywords) {
      // Only match whole words to avoid false positives
      const regex = new RegExp(`\\b${keyword}\\b`, "i");
      if (regex.test(text)) {
        return subject;
      }
    }
  }
  // Default to General Knowledge if no match
  return "General";
}
